--- #-------------------------------------------------------------------------------------------------------------

#-------------------------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See https://go.microsoft.com/fwlink/?linkid=2090316 for license information.
version: "3"
services:
  app:
    network_mode: host
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - /server:/server

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    expose:
      - "8000"

  db:
    network_mode: host
    image: quay.io/perriea/alpine-mysql:1.0
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - ./mysql-init-files/:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: "do_nation"
    expose:
      - "3306"
